/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoObjectRouteImport } from './routes/demo/object'
import { Route as DemoChatRouteImport } from './routes/demo/chat'
import { Route as ApiObjectRouteImport } from './routes/api/object'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoObjectRoute = DemoObjectRouteImport.update({
  id: '/demo/object',
  path: '/demo/object',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoChatRoute = DemoChatRouteImport.update({
  id: '/demo/chat',
  path: '/demo/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObjectRoute = ApiObjectRouteImport.update({
  id: '/api/object',
  path: '/api/object',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/object': typeof ApiObjectRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/object': typeof DemoObjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/object': typeof ApiObjectRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/object': typeof DemoObjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/object': typeof ApiObjectRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/object': typeof DemoObjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat' | '/api/object' | '/demo/chat' | '/demo/object'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/api/object' | '/demo/chat' | '/demo/object'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/object'
    | '/demo/chat'
    | '/demo/object'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiObjectRoute: typeof ApiObjectRoute
  DemoChatRoute: typeof DemoChatRoute
  DemoObjectRoute: typeof DemoObjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/object': {
      id: '/demo/object'
      path: '/demo/object'
      fullPath: '/demo/object'
      preLoaderRoute: typeof DemoObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/chat': {
      id: '/demo/chat'
      path: '/demo/chat'
      fullPath: '/demo/chat'
      preLoaderRoute: typeof DemoChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/object': {
      id: '/api/object'
      path: '/api/object'
      fullPath: '/api/object'
      preLoaderRoute: typeof ApiObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiObjectRoute: ApiObjectRoute,
  DemoChatRoute: DemoChatRoute,
  DemoObjectRoute: DemoObjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
